[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Add any environment variables that should be set for all builds
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  framework = "nextjs"

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Set Next.js specific headers and redirects
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
