[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Add any environment variables that should be set for all builds
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  framework = "nextjs"

# Exclude Supabase Edge Functions from processing
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all unmatched routes to index for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
